### ISSUE TITLE
Flarum discuss/forum thread is missing

### ISSUE THREAD

**Issue by TheDcoder** [FFans/clipboardjs#1]
Hi,

First of all, thanks for making the extension, it is very useful and better than the others I have tried. I noticed that the "[Discuss](https://discuss.flarum.org/d/26408)" link is broken, discuss.flarum.org simply returns "The page you requested could not be found." upon visiting it.

**Comment by littlegolden** [comment]
Thank you so much for pointing this, the thread link (https://discuss.flarum.org/d/26415) has changed by e8f07bc.
